import { foodIcon, topicIcons, floatingFood, papelPicado } from '../components/fiesta.js';
import {business as b, orderButton, arrow} from '../data.js';
const nav = [['/', 'Home'], ['/menu/', 'Our menu'], ['/about/', 'About us'], ['/visit/', 'Visit us']];
const logo = `<span class="wordmark"><span>TAQUERIA</span><strong>CINCO <i>de</i> MAYO</strong><small>HYATTSVILLE, MARYLAND</small></span>`;
export function layout({title, description, body, path = '/'}) {
  const links = nav.map(([url,label]) => `<a href="${url}"${path===url?' aria-current="page"':''}>${url==='/menu/'?foodIcon('taco'):''}${label}</a>`).join('');
  body = topicIcons(body);
  body = body.replace(/(<section class="(?:hero|page-intro|about-hero)">)/, '$1' + papelPicado());
  const schema = { '@context':'https://schema.org', '@type':'Restaurant', name:b.name, telephone:'+1-443-433-0240', servesCuisine:'Mexican', priceRange:'$10–20', address:{'@type':'PostalAddress', streetAddress:b.address, addressLocality:'Hyattsville',addressRegion:'MD',postalCode:'20784',addressCountry:'US'}, openingHoursSpecification:{'@type':'OpeningHoursSpecification',dayOfWeek:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],opens:'10:00',closes:'20:00'}, hasMap:b.maps, hasMenu:b.order };
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#b92127"><title>${title}</title><meta name="description" content="${description}"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:type" content="website"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Oswald:wght@500;600;700&display=swap" rel="stylesheet"><script type="application/ld+json">${JSON.stringify(schema)}</script><script src="/app.js" defer></script></head><body><a class="skip-link" href="#main">Skip to content</a><div class="topbar"><span>UN POQUITO DE MÉXICO. RIGHT HERE IN HYATTSVILLE.</span><a href="${b.directions}">7201 Annapolis Rd ${arrow}</a></div><header class="site-header"><div class="wrap header-inner"><a class="brand" href="/" aria-label="Taqueria Cinco de Mayo home">${logo}</a><nav aria-label="Main navigation">${links}</nav>${orderButton('Order online', 'header-order')}</div></header><main id="main" class="fiesta-main">${floatingFood()}${body}</main><footer><div class="wrap footer-grid"><div><a class="brand" href="/" aria-label="Taqueria Cinco de Mayo home">${logo}</a><p>Mexican flavor.<br>Neighborhood corazón.</p></div><div><h2>COME HUNGRY</h2><address>${b.address}<br>${b.city}</address><a href="${b.directions}">Get directions ${arrow}</a></div><div><h2>SAY HOLA</h2><a href="${b.tel}">${b.phone}</a><p>Daily · 10 AM–8 PM<br><small>Holiday hours may vary.</small></p></div><div><h2>TAKE A LOOK</h2><nav aria-label="Footer navigation">${links}</nav></div></div><div class="wrap footer-bottom"><button class="motion-toggle" type="button" aria-pressed="false" hidden>Pause animations</button><span>© ${new Date().getFullYear()} Taqueria Cinco de Mayo</span><span>Latino-owned. Everyone welcome.</span><span class="imagery-note">Quesabirria imagery is illustrative.</span></div></footer><div class="mobile-order-bar"><a href="/menu/">View menu</a>${orderButton('Order pickup')}</div></body></html>`;
}
